# Generated by Django 4.2.2 on 2023-06-24 19:54

from django.db import migrations, models
import django.utils.timezone
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_rename_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FilePathField(default=django.utils.timezone.now, path=images.models.images_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='tags',
            field=models.JSONField(default=dict),
        ),
    ]
