# Generated by Django 4.2.2 on 2023-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.TextField(),
        ),
    ]
