# Generated by Django 4.2.2 on 2023-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb',
            field=models.TextField(null=True),
        ),
    ]
