# Generated by Django 4.2.2 on 2023-06-24 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
