# Generated by Django 4.2.2 on 2023-07-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.TextField(default='image'),
        ),
    ]
